import { useEffect, useRef, useState } from 'react'
import { MANIFEST_URL, frameUrl, type FrameManifest } from '../lib/frameUtils'

export interface ImageSequenceState {
  /** 0-indexed: images[i] is frame file i+1 (spine_0001.webp -> images[0]). */
  images: (HTMLImageElement | null)[]
  frameCount: number
  loadedCount: number
  progress: number
  isLoading: boolean
  /** Set when the manifest itself could not be read; the site still renders. */
  error: string | null
}

const INITIAL_STATE: ImageSequenceState = {
  images: [],
  frameCount: 0,
  loadedCount: 0,
  progress: 0,
  isLoading: true,
  error: null,
}

/**
 * Preloads the spine frame sequence described by public/frames/manifest.json
 * (generated by scripts/extract-frames.js) and reports loading progress so a
 * Preloader can show it. Never throws: a missing manifest or a handful of
 * failed frames degrade gracefully instead of blocking the site.
 */
export function useImageSequence(): ImageSequenceState {
  const [state, setState] = useState<ImageSequenceState>(INITIAL_STATE)
  const cancelledRef = useRef(false)

  useEffect(() => {
    cancelledRef.current = false
    const images: (HTMLImageElement | null)[] = []
    const loadedImages: HTMLImageElement[] = []

    async function load() {
      let manifest: FrameManifest
      try {
        const res = await fetch(MANIFEST_URL)
        if (!res.ok) throw new Error(`manifest HTTP ${res.status}`)
        manifest = (await res.json()) as FrameManifest
        if (!manifest.count || manifest.count < 1) throw new Error('manifest vide')
      } catch {
        if (cancelledRef.current) return
        setState({
          ...INITIAL_STATE,
          isLoading: false,
          error:
            "Séquence d'images introuvable. Lancez `npm run extract-frames` après avoir placé la vidéo dans public/source/spine.mp4.",
        })
        return
      }

      const total = manifest.count
      images.length = total

      let settled = 0
      const bump = (img: HTMLImageElement | null, index: number) => {
        if (cancelledRef.current) return
        images[index] = img
        if (img) loadedImages.push(img)
        settled += 1
        setState({
          images: images.slice(),
          frameCount: total,
          loadedCount: settled,
          progress: settled / total,
          isLoading: settled < total,
          error: null,
        })
      }

      for (let i = 1; i <= total; i += 1) {
        const img = new Image()
        img.decoding = 'async'
        const index = i - 1
        img.onload = () => bump(img, index)
        img.onerror = () => {
          console.warn(`[useImageSequence] échec de chargement de la frame ${i}`)
          bump(null, index)
        }
        img.src = frameUrl(i, manifest)
      }
    }

    void load()

    return () => {
      cancelledRef.current = true
      for (const img of images) {
        if (img) {
          img.onload = null
          img.onerror = null
        }
      }
    }
  }, [])

  return state
}
